# Generated by Django 5.1.7 on 2025-03-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/user_files')),
            ],
        ),
    ]
